### ISSUE TITLE
Alternate OpenGL loaders?

### ISSUE THREAD

**Issue by ghost** [acdemiralp/gl#1]
Hello. Will support of alternative OpenGL loaders (glad, glbinding, GL3W)?

**Comment by acdemiralp** [comment]
Hello, I will certainly take a look at these this weekend, shouldn't be too hard since the only place glew gets called is gl::initialize(). As long as they provide the necessary OpenGL functions and types, it is trivial to support any of them.

**Comment by acdemiralp** [comment]
__Decision__: While this is possible, GLEW is the de facto standard. This library offers a single way of doing things right, which also covers loading of function pointers.
