### ISSUE TITLE
Add file "export.hpp"

### ISSUE THREAD

**Issue by porky11** [acdemiralp/gl#5]
When including this, the file `gl/export.hpp` is not found.
You probably forgot to `git add` it, because it's not in the directory `include/gl/`

**Comment by acdemiralp** [comment]
Hello, cmake automatically creates this file once you build the library. I have also added it to the repository now for convenience.

**Comment by porky11** [comment]
No, didn't help. Just including gives following error now (using clang++):
```
/usr/local/include/gl/opengl.hpp:16:1: error: unknown type name '__declspec'
GL_EXPORT bool initialize ();
^
/usr/local/include/gl/export.hpp:15:25: note: expanded from macro 'GL_EXPORT'
#      define GL_EXPORT __declspec(dllimport)
                        ^
```
