### ISSUE TITLE
gl::vertex_array has no interface for glVertexAttribPointer function.

### ISSUE THREAD

**Issue by Megaxela** [acdemiralp/gl#9]

**Comment by acdemiralp** [comment]
Hello Alex,

This is intentional since ```glVertexAttribPointer``` is succeeded by a combination of ```glVertexArrayVertexBuffer``` and ```glVertexArrayAttribFormat``` since DSA. It is not deprecated, but a better alternative exists.

You can instead use the following two for identical functionality:
```
vertex_array::set_vertex_buffer (GLuint binding_index, const buffer& buffer, GLintptr offset, GLsizei stride)
vertex_array::set_attribute_format (GLuint index, GLint size, GLenum type, bool normalized, GLuint relative_offset)
```
